name: m4d_router
description: A browser routing library for Dart
version: 0.2.14
author: Mike Mitterer <office@mikemitterer.at>
homepage: https://github.com/MikeMitterer/m4d_router

environment:
  sdk: ">=2.0.0 <3.0.0"

dependencies:
  logging: '>=0.11.3 <1.0.0'

  uri: "^0.11.0"
  validate: ^1.0.0
  
dev_dependencies:
    test: any
    mockito: any
    console_log_handler: ^1.0.0

    build_runner: any
    build_test: any
    build_web_compilers: any

    path: ^1.6.0
