name: browser_sample
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Mike Mitterer <email@example.com>

environment:
  sdk: '>=2.0.0-dev.55.0 <2.0.0'

dependencies:
  m4d_router:
    path: ../..

  console_log_handler: ^1.0.0

dev_dependencies:
  build_runner: ^0.8.7
  build_web_compilers: ^0.4.0
  sass_builder: any

